[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.env]
PORT = "8000"
MYSQLUSER = "root"
MYSQLPASSWORD = "zJICfmvmjBHIVMkHOSMvqUPIylZKamsL"
MYSQLHOST = "junction.proxy.rlwy.net"
MYSQLPORT = "14197"
MYSQL_DATABASE = "railway"